export const FeaturedCourse = [
    {
        price:1230, 
        instructor:'Thembi',
        desc: 'C++ is a powerful general-purpose programming language. It can be used to develop operating systems, browsers, games, and so on. ',  
        image: './../assets/img/featuredcourses/c++.png',
        name: 'C++ Programming',
        gradNo: 17753, 
    },
    {
        price:2564,
         instructor:'Kgothatso', 
         desc: 'Cloud computing is the provision of computing services, such as servers, storage, databases, networks, softwareCourse Description',  
         image: './../assets/img/featuredcourses/cloud.jpg',
          name: 'Cloud Computing',
        gradNo: 1773, 
    },
    {
        price:955,instructor:'Sinoxolo',
        desc: 'We Create and Collaborate to Find the Best Solution for Our Products. Software Development built using the Agile Philosohpy.',
          image: './../assets/img/featuredcourses/django.png',
           name: 'Django Python', 
           gradNo: 1543, 
    },
    {
         price:897,
         instructor:'Emmanuel',
         desc: 'the best in game development. Access industry expertise focusing on debugging, performance, and testing. Register now.', 
         image: './../assets/img/featuredcourses/gaming2.jpg', 
         name: 'Gaming Development', 
         gradNo: 14453, 
    },
    {
        price:2315,
        instructor:'Mia Sinah',
        desc: 'The Internet of things (IoT) describes the network of physical objects—“things”—that are embedded with sensors, software,',  
        image: './../assets/img/featuredcourses/iot.jpg', 
        name: 'IoT', 
        gradNo: 88443, 
    },
    {
        price:2531,
        instructor:'Innocent',
        desc: 'Robotics is an interdisciplinary field that integrates computer science and engineering. Robotics involves design, construction,',  
        image: './../assets/img/featuredcourses/robotics.jpg', 
        name: 'Robotics', 
        gradNo: 4993, 
    },
];