export const LatestCourse = [
    {
       price:1230, 
       instructor:'Thembi', 
       desc: 'C++ is a powerful general-purpose programming language. It can be used to develop operating systems, browsers, games, and so on. ',  
       image: './../assets/img/latestcourses/AI.jpg', 
       name: 'Artificial Intelligence', 
       gradNo: 17753, 
    },
    {
        price:955, 
        instructor:'Sinoxolo',
        desc: 'We Create and Collaborate to Find the Best Solution for Our Products. Software Development built using the Agile Philosohpy.',
        image: './../assets/img/latestcourses/flutter.png', 
        name: 'Flutter', 
        gradNo: 1543, 
    },
    {
        price:897, instructor:'Emmanuel',
        desc: 'the best in game development. Access industry expertise focusing on debugging, performance, and testing. Register now.',
        image: './../assets/img/latestcourses/Angular.jpg', 
        name: 'Angular',
        gradNo: 14453, 
    },
    {
        price:2315,
        instructor:'Mia Sinah',
        desc: 'The Internet of things (IoT) describes the network of physical objects—“things”—that are embedded with sensors, software,',   
        image: './../assets/img/latestcourses/gaming.jpg', 
        name: 'Game Development', 
        gradNo: 885443, 
    },
    {
        price:2531,
        instructor:'Innocent',
        desc: 'Robotics is an interdisciplinary field that integrates computer science and engineering. Robotics involves design, construction,',  
        image: './../assets/img/latestcourses/FIREBASE.jpg', 
        name: 'Google Firebase', 
        gradNo: 4993, 
    },
    {
        price:2531,
        instructor:'Kgothatso',
        desc: 'Robotics is an interdisciplinary field that integrates computer science and engineering. Robotics involves design, construction,',  
        image: './../assets/img/latestcourses/react.png', 
        name: 'React', 
        gradNo: 4993, 
    },
];
